# Generated by Django 6.0.5 on 2026-05-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='calories',
            field=models.IntegerField(default=0, help_text='Target: 500 kcal'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='distance_km',
            field=models.FloatField(default=0.0, help_text='Target: 5 km'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='it_math_hours',
            field=models.FloatField(default=0.0, help_text='Target: 1 hour'),
        ),
    ]
